PAIR-code/recommendation-rudders

LICENSE, hyperbolic-rs/LICENSE, hyperbolic-rs/README.md, hyperbolic-rs/graph_stats.py, hyperbolic-rs/preprocess.py, hyperbolic-rs/rudders/config.py, hyperbolic-rs/rudders/datasets/process_results.py, hyperbolic-rs/rudders/graph/analysis/degrees.py, hyperbolic-rs/rudders/graph/analysis/hyperbolicities.py, hyperbolic-rs/rudders/graph/analysis/nodes_per_layer.py, hyperbolic-rs/rudders/graph/analysis/plot_degrees.py, hyperbolic-rs/rudders/graph/analysis/plot_hyperbolicity.py, hyperbolic-rs/rudders/graph/analysis/plot_nodes_per_layer.py, hyperbolic-rs/rudders/graph/analysis/plot_ricci_curv.py, hyperbolic-rs/rudders/graph/analysis/plot_seccurvs.py, hyperbolic-rs/rudders/graph/analysis/ricci_curv.py, hyperbolic-rs/rudders/graph/analysis/seccurvs.py, hyperbolic-rs/rudders/graph/analysis/utils.py, hyperbolic-rs/rudders/graph/plot_seccurv.py, hyperbolic-rs/rudders/graph/seccurv.py, hyperbolic-rs/rudders/graph/utils.py, hyperbolic-rs/rudders/losses.py, hyperbolic-rs/rudders/models/base.py, hyperbolic-rs/rudders/models/complex.py, hyperbolic-rs/rudders/models/euclidean.py, hyperbolic-rs/rudders/models/hyperbolic.py, hyperbolic-rs/rudders/runner.py, hyperbolic-rs/rudders/utils.py, hyperbolic-rs/train.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pair-code/recommendation-rudders/10)
=> update to latest version with more models.

llm-recs/appengine-server/package-lock.json, llm-recs/appengine-server/package.json, llm-recs/llm-recs-webclient/src/app/app.module.ts, llm-recs/llm-recs-webclient/src/app/llm-api-config/llm-api-config.component.ts, llm-recs/llm-recs-webclient/src/app/rudders-home/rudders-home.component.ts, llm-recs/llm-recs-webclient/src/app/vertex-api.service.spec.ts, llm-recs/llm-recs-webclient/src/app/vertex-api.service.ts, llm-recs/llm-recs-webclient/src/lib/text-embeddings/embedder.ts, llm-recs/llm-recs-webclient/src/lib/text-embeddings/embedder_vertexapi.ts, llm-recs/llm-recs-webclient/src/lib/text-embeddings/scripts/run_embedder_raw.ts, llm-recs/llm-recs-webclient/src/lib/text-embeddings/scripts/tsconfig.json, llm-recs/llm-recs-webclient/src/lib/text-templates/llm_vertexapi_palm2.ts
* A small library to call and get response from Vertex API embeddings API
* Renamed Palm2 angular service to Vertex and included text embedding API
* Fixed package bug where we lost the mocha testing library
=> Initial Vertex API Integration

hyperbolic-rs/rudders/datasets/movielens.py
Changes needed for working with movie lens + IMDB synopsis (from the [MPST dataset](https://ritual.uh.edu/mpst-2018/)).
- Uses IMDB for movie IDs. 
- Loads data from a jsonl file (preprocessing to be added in a separate PR)
=> Support movie lens with IMDB synopsis

llm-recs/llm-recs-webclient/src/app/app-settings/app-settings.component.html, llm-recs/llm-recs-webclient/src/app/app-settings/app-settings.component.ts, llm-recs/llm-recs-webclient/src/app/app.module.ts, llm-recs/llm-recs-webclient/src/app/google-sheets.service.spec.ts, llm-recs/llm-recs-webclient/src/app/google-sheets.service.ts, llm-recs/llm-recs-webclient/src/app/saved-data.service.ts
* Cleanup sheets API usage (consistent handling of error)
* Fixes app data saving, so app name live updates when editting in settings. 
* Supports getting range values from a google sheet.
=> sheets api cleanup and getting values

llm-recs/llm-recs-webclient/README.md, llm-recs/llm-recs-webclient/src/app/app-settings/app-settings.component.html, llm-recs/llm-recs-webclient/src/app/app-settings/app-settings.component.ts, llm-recs/llm-recs-webclient/src/app/data-item/data-item.component.ts, llm-recs/llm-recs-webclient/src/app/data-viewer/data-viewer.component.html, llm-recs/llm-recs-webclient/src/app/data-viewer/data-viewer.component.ts, llm-recs/llm-recs-webclient/src/app/google-auth.service.ts, llm-recs/llm-recs-webclient/src/app/saved-data.service.ts, llm-recs/llm-recs-webclient/src/lib/text-embeddings/embedder_api.ts
* Fixes some more cases where edits required a refresh (where we needed to update via {...data} instead of just data in the data service. 
* Supports fetching the data from a sheet and then computing vectors (and avoids writing duplicates).
* Removes some console logging. 
* Item's now directly talk to the data service to remove data instead of raising an event.
=> Finished v1 of sheets data import

llm-recs/appengine-server/.editorconfig, llm-recs/appengine-server/package-lock.json, llm-recs/appengine-server/package.json, llm-recs/appengine-server/server.ts, llm-recs/appengine-server/src/text-embeddings/embedder_gaxois_vertexapi.ts, llm-recs/appengine-server/src/text-embeddings/scripts/run_embedder_gaxois.ts, llm-recs/appengine-server/src/text-templates/llm_gaxois_vertexapi_palm2.ts, llm-recs/appengine-server/src/text-templates/scripts/run_vertexapi_palm2_fetch_predict.ts, llm-recs/appengine-server/src/text-templates/scripts/run_vertexapi_palm2_gaxois_predict.ts, llm-recs/llm-recs-webclient/src/app/app-routing.module.ts, llm-recs/package-lock.json
- Add a gaxois version of the LLM vertex API.
- Also added an .editorconfig.
- Added underscore dependency.
- Added types for yargs.
- Some other cleanups.
=> Add a gaxois version of the LLM vertex API and some cleanups.

llm-recs/llm-recs-webclient/src/app/data-item/data-item.component.html, llm-recs/llm-recs-webclient/src/app/data-item/data-item.component.scss, llm-recs/llm-recs-webclient/src/lib/recommender-prompts/item-interpreter.ts, llm-recs/llm-recs-webclient/src/lib/text-templates/scripts/run_vertexapi_palm2_predict_rec_test.ts
* Initial LLM interpreter
* tiny UI cleanup that shouldn't really be here...
=> Initial LLM item interpreter

llm-recs/llm-recs-webclient/src/lib/text-templates/fewshot_template.spec.ts, llm-recs/llm-recs-webclient/src/lib/text-templates/template.spec.ts, llm-recs/llm-recs-webclient/src/lib/text-templates/template.ts
* Thanks to @sophie4869 for finding and fixing the bug :) 
* Allows template var to match multiple lines
* adds some more template tests
=> fix bug in template library

llm-recs/llm-recs-webclient/src/app/data-item/data-item.component.html, llm-recs/llm-recs-webclient/src/app/data-item/data-item.component.ts, llm-recs/llm-recs-webclient/src/app/saved-data.service.ts
- Moved to using template forms (not reactive forms) and more direct signal usage patten for data items.
=> data items test fix and cleanup

llm-recs/appengine-server/server.ts, llm-recs/llm-recs-webclient/src/app/data-item/data-item.component.html, llm-recs/llm-recs-webclient/src/app/data-item/data-item.component.scss, llm-recs/llm-recs-webclient/src/app/data-item/data-item.component.ts, llm-recs/llm-recs-webclient/src/app/item-interpreter.service.ts, llm-recs/llm-recs-webclient/src/app/saved-data.service.ts
- Extend the data model to have sentiment, entity details and characteristics.
- UI changes to show the new fields.
=> Extend the data model to have sentiment and entity details and characteristics and add UI support for it.

llm-meditators/webapp/src/app/exp-survey/exp-survey.component.html, llm-meditators/webapp/src/app/exp-survey/exp-survey.component.scss, llm-meditators/webapp/src/app/exp-survey/exp-survey.component.ts
Ongoing adding a slider that interacts with current stage.
=> initial slider implementation; ToDo update current Stage

llm-meditators/webapp/src/app/services/saved-data.service.ts
* adds support for parsing/setting routing params linked to local session data. 
* Organise types in saved-data.service
=> session support in URL params, and organizing types in saved-data

llm-meditators/webapp/src/app/app-home/app-home.component.html, llm-meditators/webapp/src/app/app-home/app-home.component.ts, llm-meditators/webapp/src/app/app.component.html, llm-meditators/webapp/src/app/app.component.ts, llm-meditators/webapp/src/app/app.module.ts, llm-meditators/webapp/src/app/data-model.ts, llm-meditators/webapp/src/app/exp-leader-vote/exp-leader-vote.component.ts, llm-meditators/webapp/src/app/exp-survey/exp-survey.component.ts, llm-meditators/webapp/src/app/services/saved-data.service.ts
Screencast... 
https://github.com/PAIR-code/recommendation-rudders/assets/415450/674fead2-7ee0-480c-ac28-5cdcbf561207
=> dynamically change components as the stage changes

llm-meditators/webapp/README.md, llm-meditators/webapp/src/app/app-home/app-home.component.html, llm-meditators/webapp/src/app/app.component.html, llm-meditators/webapp/src/app/app.component.ts, llm-meditators/webapp/src/app/app.module.ts, llm-meditators/webapp/src/app/exp-chat/exp-chat.component.html, llm-meditators/webapp/src/app/exp-chat/exp-chat.component.spec.ts, llm-meditators/webapp/src/app/exp-chat/exp-chat.component.ts, llm-meditators/webapp/src/app/exp-leader-vote/exp-leader-vote.component.spec.ts, llm-meditators/webapp/src/app/exp-leader-vote/exp-leader-vote.component.ts, llm-meditators/webapp/src/app/exp-profile/exp-profile.component.html, llm-meditators/webapp/src/app/exp-profile/exp-profile.component.spec.ts, llm-meditators/webapp/src/app/exp-profile/exp-profile.component.ts, llm-meditators/webapp/src/app/exp-rating/exp-rating.component.html, llm-meditators/webapp/src/app/exp-rating/exp-rating.component.spec.ts, llm-meditators/webapp/src/app/exp-rating/exp-rating.component.ts, llm-meditators/webapp/src/app/exp-survey/exp-survey.component.spec.ts, llm-meditators/webapp/src/app/exp-survey/exp-survey.component.ts, llm-meditators/webapp/src/app/services/saved-data.service.ts, llm-meditators/webapp/src/lib/staged-exp/data-model.ts, llm-meditators/webapp/src/lib/staged-exp/example-experiment.ts, llm-meditators/webapp/src/lib/staged-exp/items.ts
* Moves data model and the example experiment into it's own directory in `lib/staged-exp` and fleshed out more stages of the experiment. 
* Creates new empty components for more missing stage-kinds in the experiment.
=> create higher fidelity experiment & more components

llm-meditators/webapp/src/app/app-home/app-home.component.html, llm-meditators/webapp/src/app/app.component.html, llm-meditators/webapp/src/app/exp-chat/chat-discuss-items-message/chat-discuss-items-message.component.html, llm-meditators/webapp/src/app/exp-chat/chat-discuss-items-message/chat-discuss-items-message.component.spec.ts, llm-meditators/webapp/src/app/exp-chat/chat-discuss-items-message/chat-discuss-items-message.component.ts, llm-meditators/webapp/src/app/exp-chat/chat-mediator-message/chat-mediator-message.component.html, llm-meditators/webapp/src/app/exp-chat/chat-mediator-message/chat-mediator-message.component.spec.ts, llm-meditators/webapp/src/app/exp-chat/chat-mediator-message/chat-mediator-message.component.ts, llm-meditators/webapp/src/app/exp-chat/chat-user-message/chat-user-message.component.html, llm-meditators/webapp/src/app/exp-chat/chat-user-message/chat-user-message.component.spec.ts, llm-meditators/webapp/src/app/exp-chat/chat-user-message/chat-user-message.component.ts, llm-meditators/webapp/src/app/exp-chat/chat-user-profile/chat-user-profile.component.html, llm-meditators/webapp/src/app/exp-chat/chat-user-profile/chat-user-profile.component.scss, llm-meditators/webapp/src/app/exp-chat/chat-user-profile/chat-user-profile.component.spec.ts, llm-meditators/webapp/src/app/exp-chat/chat-user-profile/chat-user-profile.component.ts, llm-meditators/webapp/src/app/exp-chat/exp-chat.component.html, llm-meditators/webapp/src/app/exp-chat/exp-chat.component.ts, llm-meditators/webapp/src/app/exp-chat/mediator-feedback/mediator-feedback.component.html, llm-meditators/webapp/src/app/exp-chat/mediator-feedback/mediator-feedback.component.spec.ts, llm-meditators/webapp/src/app/exp-chat/mediator-feedback/mediator-feedback.component.ts, llm-meditators/webapp/src/app/exp-leader-vote/exp-leader-vote.component.html, llm-meditators/webapp/src/app/exp-leader-vote/exp-leader-vote.component.ts, llm-meditators/webapp/src/app/exp-profile/exp-profile.component.ts, llm-meditators/webapp/src/app/services/saved-data.service.ts, llm-meditators/webapp/src/lib/staged-exp/data-model.ts, llm-meditators/webapp/src/lib/staged-exp/example-experiment.ts
* Adds some initial components for chat
* A little cleanup of how we create experiments
* Voting components logic linked to the data model
* Adds a concept of a stage being "complete"
=> initial chat skeleton and participants

llm-meditators/webapp/src/app/app-home/app-home.component.html, llm-meditators/webapp/src/app/app-home/app-home.component.ts, llm-meditators/webapp/src/app/app.component.html, llm-meditators/webapp/src/app/app.component.ts, llm-meditators/webapp/src/app/app.module.ts, llm-meditators/webapp/src/app/exp-chat/chat-user-message/chat-user-message.component.html, llm-meditators/webapp/src/app/exp-chat/chat-user-message/chat-user-message.component.ts, llm-meditators/webapp/src/app/exp-chat/chat-user-profile/chat-user-profile.component.html, llm-meditators/webapp/src/app/exp-chat/exp-chat.component.html, llm-meditators/webapp/src/app/exp-chat/exp-chat.component.ts, llm-meditators/webapp/src/app/exp-leader-vote/exp-leader-vote.component.html, llm-meditators/webapp/src/app/exp-leader-vote/exp-leader-vote.component.ts, llm-meditators/webapp/src/app/exp-profile/exp-profile.component.html, llm-meditators/webapp/src/app/exp-profile/exp-profile.component.ts, llm-meditators/webapp/src/app/exp-rating/exp-rating.component.ts, llm-meditators/webapp/src/app/exp-survey/exp-survey.component.html, llm-meditators/webapp/src/app/exp-survey/exp-survey.component.ts, llm-meditators/webapp/src/app/exp-tos-and-profile/exp-tos-and-profile.component.html, llm-meditators/webapp/src/app/exp-tos-and-profile/exp-tos-and-profile.component.scss, llm-meditators/webapp/src/app/exp-tos-and-profile/exp-tos-and-profile.component.spec.ts, llm-meditators/webapp/src/app/exp-tos-and-profile/exp-tos-and-profile.component.ts, llm-meditators/webapp/src/app/exp-tos/exp-tos.component.html, llm-meditators/webapp/src/app/exp-tos/exp-tos.component.ts, llm-meditators/webapp/src/app/services/saved-data.service.ts, llm-meditators/webapp/src/lib/staged-exp/data-model.ts, llm-meditators/webapp/src/lib/staged-exp/example-experiment.ts
* A bit of refactoring of how we talk to the data model (preparing for firebase integration)
* Initial chat
=> Data refactor preparing for Firebase & initial chat

llm-meditators/webapp/src/app/exp-leader-vote/exp-leader-vote.component.ts, llm-meditators/webapp/src/app/exp-rating/exp-rating.component.html, llm-meditators/webapp/src/app/exp-rating/exp-rating.component.scss, llm-meditators/webapp/src/app/exp-rating/exp-rating.component.ts, llm-meditators/webapp/src/app/exp-tos-and-profile/exp-tos-and-profile.component.html, llm-meditators/webapp/src/lib/staged-exp/data-model.ts, llm-meditators/webapp/src/lib/staged-exp/example-experiment.ts
=> updated rating component

llm-meditators/webapp/package-lock.json, llm-meditators/webapp/package.json, llm-meditators/webapp/src/app/app-home/app-home.component.html, llm-meditators/webapp/src/app/app-home/app-home.component.ts, llm-meditators/webapp/src/app/app-settings/app-settings.component.html, llm-meditators/webapp/src/app/app-settings/app-settings.component.scss, llm-meditators/webapp/src/app/app-settings/app-settings.component.ts, llm-meditators/webapp/src/app/app.component.html, llm-meditators/webapp/src/app/app.component.ts, llm-meditators/webapp/src/app/app.module.ts, llm-meditators/webapp/src/app/exp-leader-reveal/exp-leader-reveal.component.html, llm-meditators/webapp/src/app/exp-leader-reveal/exp-leader-reveal.component.scss, llm-meditators/webapp/src/app/exp-leader-reveal/exp-leader-reveal.component.spec.ts, llm-meditators/webapp/src/app/exp-leader-reveal/exp-leader-reveal.component.ts, llm-meditators/webapp/src/app/services/saved-data.service.ts, llm-meditators/webapp/src/lib/staged-exp/data-model.ts, llm-meditators/webapp/src/lib/staged-exp/example-experiment.ts, llm-meditators/webapp/tsconfig.json
- easily fake the switch of current user
- wait while all other users reach the final stage
=> setting up the final leader reveal component

llm-meditators/webapp/src/app/app-home/app-home.component.html, llm-meditators/webapp/src/app/app-home/app-home.component.scss, llm-meditators/webapp/src/app/app-home/app-home.component.ts, llm-meditators/webapp/src/app/experimenter-view/experiment-monitor/experiment-monitor.component.html, llm-meditators/webapp/src/app/experimenter-view/experiment-monitor/experiment-monitor.component.scss, llm-meditators/webapp/src/app/experimenter-view/experiment-monitor/experiment-monitor.component.ts, llm-meditators/webapp/src/app/participant-view/participant-stage-view/exp-survey/exp-survey.component.ts, llm-meditators/webapp/src/app/participant-view/participant-stage-view/participant-stage-view.component.html, llm-meditators/webapp/src/app/participant-view/participant-stage-view/participant-stage-view.component.ts, llm-meditators/webapp/src/app/participant-view/participant-view.component.scss, llm-meditators/webapp/src/app/participant-view/participant-view.component.ts, llm-meditators/webapp/src/app/services/app-state.service.ts, llm-meditators/webapp/src/app/valid-participant.guard.ts, llm-meditators/webapp/src/lib/albebraic-data.ts, llm-meditators/webapp/src/lib/staged-exp/app.ts, llm-meditators/webapp/src/lib/staged-exp/participant.ts
* Make access codes work
* Remove some dead commented out code
* Use enum for app state
* use an `@case` for selecting stages
=> cleamup, and make access codes work

llm-meditators/webapp/src/app/participant-view/participant-stage-view/exp-chat/exp-chat.component.html, llm-meditators/webapp/src/app/participant-view/participant-stage-view/exp-chat/exp-chat.component.scss, llm-meditators/webapp/src/app/participant-view/participant-stage-view/exp-chat/exp-chat.component.ts
Put your own profile next to your send message text box, so you are primed to know how you will be presenting yourself in chat
=> own profile before sending message

llm-meditators/webapp/src/app/app-routing.module.ts, llm-meditators/webapp/src/app/app.module.ts, llm-meditators/webapp/src/app/experimenter-view/experimenter-view.component.html, llm-meditators/webapp/src/app/experimenter-view/llm-api-config/llm-api-config.component.html, llm-meditators/webapp/src/app/experimenter-view/llm-api-config/llm-api-config.component.scss, llm-meditators/webapp/src/app/experimenter-view/llm-api-config/llm-api-config.component.spec.ts, llm-meditators/webapp/src/app/experimenter-view/llm-api-config/llm-api-config.component.ts, llm-meditators/webapp/src/app/experimenter-view/mediator-chat/mediator-chat.component.html, llm-meditators/webapp/src/app/experimenter-view/mediator-chat/mediator-chat.component.ts
- Enter your credentials in the tab LLM Settings
- In the Experimenter Chat view, click Send under the Automated Mediation Section to push LLM-generated messages. 
ToDo: 
- Edit template
- Edit the model called (Can we have calls to Gemini through Vertex AI?)
- Automate the calls themselves, like after every N messages, or even better: trigger the need for mediation automatically
=> First implementation of Vertex API calls made by the Human mediator

llm-meditators/webapp/src/app/participant-view/participant-stage-view/exp-chat/exp-chat.component.html, llm-meditators/webapp/src/app/participant-view/participant-stage-view/exp-chat/exp-chat.component.ts, llm-meditators/webapp/src/app/participant-view/participant-stage-view/exp-leader-reveal/exp-leader-reveal.component.ts, llm-meditators/webapp/src/app/participant-view/participant-stage-view/exp-tos-and-profile/exp-tos-and-profile.component.ts, llm-meditators/webapp/src/app/participant-view/participant-stage-view/participant-stage-view.component.html, llm-meditators/webapp/src/app/participant-view/participant-stage-view/participant-stage-view.component.ts, llm-meditators/webapp/src/lib/staged-exp/data-model.ts, llm-meditators/webapp/src/lib/staged-exp/example-experiment.ts
* Add field setup values during profile setup.
* Fix "isSilent" toggle functionality during the conversation stage.
* To do: survey question completion criteria.
=> Disable stage map progression depending on stage-specific criteria.
